export const SET_LEVEL_NODE = 'SET_LEVEL_NODE';
export const SET_CHOICES = 'SET_CHOICES';
export const SET_LEVEL_MOOD = 'SET_LEVEL_MOOD';
export const SET_LEVEL_INVENTORY = 'SET_LEVEL_INVENTORY';
export const SET_RESPONSES = 'SET_RESPONSES';
export const SET_DECISION = 'SET_DECISION';
export const CLEAR_GAME_DATA = 'CLEAR_GAME_DATA';
